For this lab we will build a model on customer churn binary classification problem.
You will be using DATA_Customer-Churn file that you can find in this LINK.

Scenario

You are working as an analyst with this internet service provider.
You are provided with this historical data about your company's customers and their churn trends.
Your task is to build a machine learning model that will help the company identify customers that are more likely to default/churn and thus prevent losses from such customers.

Instructions

In this lab, we will first take a look at the degree of imbalance in the data and correct it using the techniques we learned on the class. Here is the list of steps to be followed (building a simple model without balancing the data):

Round 1

 - Import the required libraries and modules that you would need.
 - Read that data into Python and call the dataframe churnData.
 - Check the datatypes of all the columns in the data.You would see that the column TotalCharges is object type.  
 - Convert this column into numeric type using pd.to_numeric function.
 - Check for null values in the dataframe. Replace the null values.
 - Use the following features: tenure, SeniorCitizen, MonthlyCharges and TotalCharges:
 - Split the data into a training set and a test set.
 - Scale the features either by using MinMaxScaler or a standard scaler.
- (Optional) Encode the categorical variables so you can use them for modeling later.


In [1]:
# Load Modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, confusion_matrix, precision_score, recall_score, accuracy_score, f1_score

In [2]:
df = pd.read_csv('DATA_Customer-Churn.txt', sep=",")
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

  OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0             No          Yes               No          No          No   
1            Yes           No              Yes          No          No   
2            Yes          Yes               No          No          No   
3            Yes           No              Yes         Yes          No   
4             No           No               No          No          No   

  StreamingMovies        Contract  MonthlyCharges TotalCharges Churn  
0              No  Month-to-month           29.85        29.85    No  
1              No        One year           56.95       1889.5    No  
2              No  Month-to-month           53.85       108.15   Yes  
3              No        One year           42.30      1840.75    No  
4              No  Month-to-month           70.70       151.65   Yes

In [3]:
df.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [4]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

  OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0             No          Yes               No          No          No   
1            Yes           No              Yes          No          No   
2            Yes          Yes               No          No          No   
3            Yes           No              Yes         Yes          No   
4             No           No               No          No          No   

  StreamingMovies        Contract  MonthlyCharges  TotalCharges Churn  
0              No  Month-to-month           29.85         29.85    No  
1              No        One year           56.95       1889.50    No  
2              No  Month-to-month           53.85        108.15   Yes  
3              No        One year           42.30       1840.75    No  
4              No  Month-to-month           70.70        151.65   Yes

In [5]:
df = df.fillna(-1) 

In [6]:
X = df[['tenure', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges']]

In [7]:
X.dtypes

tenure              int64
SeniorCitizen       int64
MonthlyCharges    float64
TotalCharges      float64
dtype: object

In [8]:
y = df['Churn']
y = y.map(dict({'Yes': 1, 'No': 0}))
y.dtypes

dtype('int64')

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
X_train.shape, y_train.shape, y_test.shape

((5634, 4), (5634,), (1409,))

In [11]:
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()
# transform data
min_max_scaled = minmax_scaler.fit_transform(X_train)
print(min_max_scaled)

[[0.29166667 0.         0.46437469 0.15402151]
 [0.75       0.         0.78674639 0.59067098]
 [0.01388889 0.         0.05181863 0.00281494]
 ...
 [0.16666667 0.         0.02889885 0.0353508 ]
 [0.16666667 1.         0.80916791 0.13828893]
 [0.36111111 0.         0.01544594 0.05276428]]


In [12]:
from sklearn.preprocessing import StandardScaler


std_scaler = StandardScaler()
# transform data
std_scaled = std_scaler.fit_transform(X_train)
print(std_scaled)

[[-4.65683364e-01 -4.37749204e-01 -4.73723375e-04 -4.19923404e-01]
 [ 8.85536787e-01 -4.37749204e-01  1.07475386e+00  1.25601648e+00]
 [-1.28460467e+00 -4.37749204e-01 -1.37649913e+00 -1.00028164e+00]
 ...
 [-8.34197950e-01 -4.37749204e-01 -1.45294499e+00 -8.75403091e-01]
 [-8.34197950e-01  2.28441306e+00  1.14953785e+00 -4.80307881e-01]
 [-2.60953038e-01 -4.37749204e-01 -1.49781538e+00 -8.08566998e-01]]


Round 2

    (Optional) Fit a logistic Regression model on the training data.
   - Fit a Knn Classifier (NOT KnnRegressor please!)model on the training data.
   - Fit a Decision Tree Classifier on the training data.
   - Compare the accuracy, precision, recall for the previous models on both the train and test sets.

In [13]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier()
neigh.fit(X_train, y_train)
y_pred_neigh = neigh.predict(X_test)

In [14]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train, y_train)
y_pred_clf = clf.predict(X_test)

In [17]:
display(f"Confusion matrix KNN:", confusion_matrix(y_test, y_pred_neigh))
display(f"Confusion matrix Decision Tree:", confusion_matrix(y_test, y_pred_clf))
print()
print(f"Precission Score KNN: {precision_score(y_test, y_pred_neigh)}, Precission Score Decision Tree:  {accuracy_score(y_test, y_pred_clf)} \n")
print(f"Recall Score KNN: {recall_score(y_test, y_pred_neigh)}, Recall Score Decision Tree: {accuracy_score(y_test, y_pred_clf)}\n")
print(f"F1 Score KNN: {f1_score(y_test, y_pred_neigh)}, F1 Score Decision Tree: {accuracy_score(y_test, y_pred_clf)}\n")
print(f"Accuracy Score KNN: {accuracy_score(y_test, y_pred_neigh)}, Accuracy Score Decision Tree: {accuracy_score(y_test, y_pred_clf)}")

'Confusion matrix KNN:'

array([[924, 112],
       [195, 178]])

'Confusion matrix Decision Tree:'

array([[852, 184],
       [184, 189]])


Precission Score KNN: 0.6137931034482759, Precission Score Decision Tree:  0.7388218594748048 

Recall Score KNN: 0.4772117962466488, Recall Score Decision Tree: 0.7388218594748048

F1 Score KNN: 0.5369532428355958, F1 Score Decision Tree: 0.7388218594748048

Accuracy Score KNN: 0.7821149751596878, Accuracy Score Decision Tree: 0.7388218594748048


Round 3

    apply K-fold cross validation on your models built before,  and check the model score. Note: So far we have not balanced the data.

In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

kf = KFold(n_splits=2)
#kf = KFold(3, True, 1) 

kf.get_n_splits(X_train)

2

Round 4

    fit a Random forest Classifier on the data and compare the accuracy.
    tune the hyper parameters with Gridsearch and check the results. retrain the final mode with the best parameters found.

Managing imbalance in the dataset

    Check for the imbalance.
    Use the resampling strategies used in class for upsampling and downsampling to create a balance between the two classes.
    Each time fit the model and check the accuracy of the model.